In [1]:
import numpy as np

In [3]:
# генерируем дискретную величину
np.random.randint(1, 5)

3

In [4]:
np.random.randint(1, 5, 100)

array([4, 3, 2, 3, 1, 3, 4, 2, 4, 2, 3, 4, 3, 3, 1, 3, 3, 4, 1, 1, 4, 4,
       1, 3, 4, 1, 3, 2, 3, 2, 4, 1, 1, 1, 1, 4, 4, 3, 4, 4, 4, 2, 2, 2,
       1, 3, 4, 4, 3, 3, 1, 4, 4, 4, 2, 2, 4, 3, 2, 3, 3, 1, 1, 1, 2, 2,
       4, 1, 3, 3, 1, 1, 3, 3, 2, 3, 1, 1, 3, 2, 1, 3, 2, 1, 1, 4, 1, 1,
       1, 4, 1, 4, 3, 2, 1, 1, 1, 4, 1, 1])

In [5]:
# генерируем непрерывную величину
np.random.random(100)

array([0.36622613, 0.52042049, 0.7873794 , 0.89915444, 0.36771647,
       0.01155147, 0.63298647, 0.86123852, 0.79374039, 0.10947419,
       0.47602128, 0.52273148, 0.20322603, 0.4614738 , 0.53686719,
       0.63327178, 0.30776899, 0.21664434, 0.66849465, 0.65742485,
       0.09948151, 0.91730562, 0.00858905, 0.38829581, 0.56078992,
       0.61889498, 0.36459436, 0.64346752, 0.36121922, 0.18888825,
       0.20743807, 0.67020481, 0.07582784, 0.19012729, 0.72491209,
       0.88695402, 0.81012454, 0.00477421, 0.49309512, 0.06586528,
       0.6699677 , 0.74529458, 0.99462216, 0.12565059, 0.28622109,
       0.93525494, 0.25133142, 0.83925788, 0.88422633, 0.94045246,
       0.08138539, 0.7094451 , 0.94204609, 0.16819705, 0.37696684,
       0.05855849, 0.53523425, 0.68406029, 0.33874769, 0.22096538,
       0.2915204 , 0.32513545, 0.6021612 , 0.24815073, 0.46708738,
       0.44730649, 0.18145459, 0.5548857 , 0.62405586, 0.82581044,
       0.4799131 , 0.56804574, 0.92439226, 0.02993129, 0.54040

In [8]:
np.random.uniform(1, 5)

1.5518733178678419

In [9]:
np.random.uniform(1, 5, 100)

array([1.4153742 , 4.80682711, 4.72271337, 4.70976152, 4.64274781,
       4.11632055, 4.50887525, 4.79887367, 2.62224836, 2.1383158 ,
       1.36940529, 2.99667516, 2.42388336, 3.63860158, 1.71891999,
       1.04384771, 4.92438174, 2.97369224, 3.80890864, 4.18165565,
       2.24937606, 1.74658937, 3.06107468, 1.05006136, 1.01470142,
       4.62989237, 4.84573039, 3.12975869, 2.99486458, 3.00575205,
       2.40700716, 3.99245719, 1.12882654, 3.99965956, 3.04031906,
       4.84151652, 1.53412296, 1.40355168, 1.16267299, 2.05839938,
       3.49731722, 3.71112547, 1.95298132, 2.01237687, 3.03058024,
       3.86600815, 1.55128723, 4.23905342, 2.48884524, 3.52193223,
       2.1063856 , 4.37221706, 2.22536346, 3.26719804, 1.91075058,
       3.42178687, 4.42362049, 2.12275576, 4.2447383 , 3.36136267,
       3.08650844, 1.40231802, 3.63611398, 1.48290192, 2.11823551,
       4.47899123, 3.26137209, 4.16012763, 3.29029582, 1.63851147,
       3.97594428, 3.34043792, 3.357973  , 4.41565504, 1.30742

**Задача 1.** Оценить вероятность того, что на игральной кости выпадет больше 4 очков. Сравнить с теоретической вероятностью.

In [ ]:
import numpy as np
# np.random.seed(None)
trials = 1000    # Количество попыток
successes = 0    # Количество успехов

for i in range(trials):
    random_score = np.random.randint(1, 7)    # Случайное количество очков от 1 до 6
    if random_score > 4:
        successes += 1
        
p_monte_carlo = successes / trials    # Вероятность из моделирования
p = 2 / 6                             # Теоретическая вероятность

print(successes, trials, p_monte_carlo, p)

**Задача 1А** (опциональная). Дан квадрат, в который вписан круг (касаясь сторон квадрата). В квадрат случайным образом попадают точки. Какова вероятность, что наугад взятая точка попадёт в круг?  
_Подсказка:_ Удобно взять квардат со стороной, равной 2, и отсчитывать координаты точек от его центра.

**Задача 2.** Смоделировать стрельбу по мишени.

In [ ]:
import matplotlib.pyplot as plt

shots = 1000    # Количество выстрелов
std_dev = 1 # Стандартное отклонение (на сколько мы в среднем будем мазать)

x = np.random.normal(0, std_dev, shots) # 0 - и среднее, и мода, и медиана
y = np.random.normal(0, std_dev, shots)


plt.scatter(x, y)
# почему разброс от -3 до 3?

**Задача 3.** Графически определить распределение измеренных значений физической величины, когда измерительный прибор имеет случайную погрешность.

In [ ]:
import pandas as pd

data = pd.read_csv("data.log", sep=" ")["az"]
data.describe()

In [ ]:
data.plot()

In [ ]:
plt.hist(uni, bins=11)
plt.show()
plt.hist(normal, bins=11)
plt.show()
plt.hist(data, bins=11)
plt.show()

**Задача 4.** Рассчитать вероятность того, что пациент заражён COVID-19, если известно, что тест дал положительный результат. Сравнить с результатом моделирования.

In [ ]:
prev = 0.50    # Распространённость болезни
sens = 0.95    # Чувствительность теста
spec = 0.80    # Специфичность теста

p = (sens * prev) / (sens * prev + (1 - spec) * (1 - prev))   # Теоретическая вероятность 
print(p)

In [ ]:
population = 100    # Количество испытуемых

true_pos = 0    # Количество больных с положительным тестом
false_pos = 0   # Количество здоровых с положительным тестом

for i in range(population):
    # Наугад решаем, заражён ли человек
    # для этого генерируем случайную величину от 0 до 1     
    infected = np.random.uniform() < prev
    
    # Наугад решаем, дал ли тест положительный результат 
    positive = np.random.uniform() < sens if infected else np.random.uniform() < 1 - spec
    
    if positive:
        if infected:
            true_pos += 1
        else:
            false_pos += 1
            
p_monte_carlo = true_pos / (true_pos + false_pos)    # Вероятность из моделирования
print(p_monte_carlo)